#!/bin/bash
# Load Secrets Script
# Loads secrets from GitHub Secrets or environment variables

set -e

echo "🔐 Loading Secrets for SymphAIny Platform"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if secret is set
check_secret() {
    local secret_name=$1
    local secret_value=$2
    
    if [ -z "$secret_value" ]; then
        print_error "$secret_name is not set"
        return 1
    else
        print_success "$secret_name is configured"
        return 0
    fi
}

# Function to create .env.secrets file
create_env_secrets() {
    print_status "Creating .env.secrets file..."
    
    cat > .env.secrets << EOF
# SymphAIny Platform - Secrets Configuration
# Generated by load-secrets.sh
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

# Database Configuration
DATABASE_URL=${DATABASE_URL:-http://localhost:8529}
REDIS_URL=${REDIS_URL:-redis://localhost:6379}

# Security Configuration
SECRET_KEY=${SECRET_KEY:-sk-1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef}
JWT_SECRET=${JWT_SECRET:-jwt-secret-key-change-in-production}

# External Services
SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}
SUPABASE_KEY=${SUPABASE_KEY:-your-supabase-anon-key}

# LLM Configuration
OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-your-anthropic-api-key}

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID:-your-project-id}
GOOGLE_CLOUD_CREDENTIALS=${GOOGLE_CLOUD_CREDENTIALS:-path/to/credentials.json}

# Monitoring Configuration
SENTRY_DSN=${SENTRY_DSN:-your-sentry-dsn}
DATADOG_API_KEY=${DATADOG_API_KEY:-your-datadog-api-key}
EOF

    print_success ".env.secrets file created"
}

# Check if we're in GitHub Actions
if [ "$GITHUB_ACTIONS" = "true" ]; then
    print_status "Running in GitHub Actions - using GitHub Secrets"
    
    # Check required secrets
    print_status "Checking required secrets..."
    
    check_secret "DATABASE_URL" "${{ secrets.DATABASE_URL }}"
    check_secret "REDIS_URL" "${{ secrets.REDIS_URL }}"
    check_secret "SECRET_KEY" "${{ secrets.SECRET_KEY }}"
    check_secret "JWT_SECRET" "${{ secrets.JWT_SECRET }}"
    check_secret "SUPABASE_URL" "${{ secrets.SUPABASE_URL }}"
    check_secret "SUPABASE_KEY" "${{ secrets.SUPABASE_KEY }}"
    
    # Create .env.secrets from GitHub Secrets
    cat > .env.secrets << EOF
# SymphAIny Platform - Secrets Configuration
# Generated from GitHub Secrets

# Database Configuration
DATABASE_URL=${{ secrets.DATABASE_URL }}
REDIS_URL=${{ secrets.REDIS_URL }}

# Security Configuration
SECRET_KEY=${{ secrets.SECRET_KEY }}
JWT_SECRET=${{ secrets.JWT_SECRET }}

# External Services
SUPABASE_URL=${{ secrets.SUPABASE_URL }}
SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

# LLM Configuration
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
GOOGLE_CLOUD_CREDENTIALS=${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

# Monitoring Configuration
SENTRY_DSN=${{ secrets.SENTRY_DSN }}
DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}
EOF

    print_success "Secrets loaded from GitHub Secrets"
    
else
    print_status "Running locally - using environment variables"
    
    # Check required environment variables
    print_status "Checking required environment variables..."
    
    check_secret "DATABASE_URL" "$DATABASE_URL"
    check_secret "REDIS_URL" "$REDIS_URL"
    check_secret "SECRET_KEY" "$SECRET_KEY"
    check_secret "JWT_SECRET" "$JWT_SECRET"
    check_secret "SUPABASE_URL" "$SUPABASE_URL"
    check_secret "SUPABASE_KEY" "$SUPABASE_KEY"
    
    # Create .env.secrets from environment variables
    create_env_secrets
    
    print_success "Secrets loaded from environment variables"
fi

# Validate secrets file
print_status "Validating secrets file..."
if [ -f ".env.secrets" ]; then
    print_success ".env.secrets file exists"
    
    # Check if secrets file has content
    if [ -s ".env.secrets" ]; then
        print_success ".env.secrets file has content"
    else
        print_error ".env.secrets file is empty"
        exit 1
    fi
    
    # Check for placeholder values
    if grep -q "your-.*-key" .env.secrets; then
        print_warning "Found placeholder values in .env.secrets"
        print_warning "Please update with real values before production use"
    fi
    
else
    print_error ".env.secrets file not created"
    exit 1
fi

print_success "Secrets loading complete!"
echo ""
echo "📋 Next steps:"
echo "  1. Review .env.secrets file"
echo "  2. Update placeholder values with real secrets"
echo "  3. Test configuration loading"
echo "  4. Deploy to production"
echo ""
echo "🔐 Security reminder:"
echo "  - Never commit .env.secrets to version control"
echo "  - Use GitHub Secrets for production"
echo "  - Rotate secrets regularly"
echo "  - Monitor for secret exposure"




