#!/bin/bash
# Setup Test Infrastructure for Business Enablement Realm Tests
# This script sets up GCS test bucket and Supabase test isolation

set -e  # Exit on error

echo "🚀 Setting up Test Infrastructure for Business Enablement Realm Tests"
echo "======================================================================"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    echo -e "${RED}❌ Error: gcloud CLI is not installed${NC}"
    echo "Please install Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Get project ID
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
if [ -z "$PROJECT_ID" ]; then
    echo -e "${YELLOW}⚠️  No default project set. Please set it:${NC}"
    echo "   gcloud config set project YOUR_PROJECT_ID"
    exit 1
fi

echo -e "${GREEN}✅ Using project: ${PROJECT_ID}${NC}"

# Configuration
TEST_BUCKET_NAME="symphainy-bucket-2025-test"
TEST_REGION="us-central1"
SERVICE_ACCOUNT_NAME="test-service-account"
SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
CREDENTIALS_FILE="test-credentials.json"

# Step 1: Create GCS Test Bucket
echo ""
echo "📦 Step 1: Creating GCS Test Bucket..."
if gsutil ls -b "gs://${TEST_BUCKET_NAME}" &> /dev/null; then
    echo -e "${YELLOW}⚠️  Bucket ${TEST_BUCKET_NAME} already exists${NC}"
else
    echo "   Creating bucket: ${TEST_BUCKET_NAME}"
    gsutil mb -p "${PROJECT_ID}" -l "${TEST_REGION}" "gs://${TEST_BUCKET_NAME}"
    echo -e "${GREEN}✅ Bucket created successfully${NC}"
fi

# Step 2: Set Lifecycle Policy
echo ""
echo "🔄 Step 2: Setting Lifecycle Policy (auto-delete test files after 7 days)..."
LIFECYCLE_FILE=$(mktemp)
cat > "${LIFECYCLE_FILE}" << EOF
{
  "lifecycle": {
    "rule": [
      {
        "action": {"type": "Delete"},
        "condition": {
          "age": 7,
          "matchesPrefix": ["test/"]
        }
      }
    ]
  }
}
EOF

gsutil lifecycle set "${LIFECYCLE_FILE}" "gs://${TEST_BUCKET_NAME}"
rm "${LIFECYCLE_FILE}"
echo -e "${GREEN}✅ Lifecycle policy set successfully${NC}"

# Step 3: Create Service Account
echo ""
echo "👤 Step 3: Creating Test Service Account..."
if gcloud iam service-accounts describe "${SERVICE_ACCOUNT_EMAIL}" &> /dev/null; then
    echo -e "${YELLOW}⚠️  Service account ${SERVICE_ACCOUNT_EMAIL} already exists${NC}"
else
    echo "   Creating service account: ${SERVICE_ACCOUNT_NAME}"
    gcloud iam service-accounts create "${SERVICE_ACCOUNT_NAME}" \
        --display-name="Test Service Account" \
        --description="Service account for integration tests" \
        --project="${PROJECT_ID}"
    echo -e "${GREEN}✅ Service account created successfully${NC}"
fi

# Step 4: Grant Permissions
echo ""
echo "🔐 Step 4: Granting Permissions..."
echo "   Granting Storage Object Admin role..."
gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SERVICE_ACCOUNT_EMAIL}" \
    --role="roles/storage.objectAdmin" \
    --condition=None \
    --quiet || echo -e "${YELLOW}⚠️  Permission may already be granted${NC}"

echo -e "${GREEN}✅ Permissions granted${NC}"

# Step 5: Create and Download Key
echo ""
echo "🔑 Step 5: Creating Service Account Key..."
if [ -f "${CREDENTIALS_FILE}" ]; then
    echo -e "${YELLOW}⚠️  Credentials file ${CREDENTIALS_FILE} already exists${NC}"
    read -p "   Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Skipping key creation"
    else
        gcloud iam service-accounts keys create "${CREDENTIALS_FILE}" \
            --iam-account="${SERVICE_ACCOUNT_EMAIL}" \
            --project="${PROJECT_ID}"
        echo -e "${GREEN}✅ Key created: ${CREDENTIALS_FILE}${NC}"
    fi
else
    gcloud iam service-accounts keys create "${CREDENTIALS_FILE}" \
        --iam-account="${SERVICE_ACCOUNT_EMAIL}" \
        --project="${PROJECT_ID}"
    echo -e "${GREEN}✅ Key created: ${CREDENTIALS_FILE}${NC}"
fi

# Step 6: Verify Setup
echo ""
echo "✅ Step 6: Verifying Setup..."
if gsutil ls -b "gs://${TEST_BUCKET_NAME}" &> /dev/null; then
    echo -e "${GREEN}✅ GCS bucket verified${NC}"
else
    echo -e "${RED}❌ GCS bucket verification failed${NC}"
    exit 1
fi

if [ -f "${CREDENTIALS_FILE}" ]; then
    echo -e "${GREEN}✅ Credentials file exists${NC}"
else
    echo -e "${RED}❌ Credentials file not found${NC}"
    exit 1
fi

# Step 7: Create .env.test file
echo ""
echo "📝 Step 7: Creating .env.test configuration..."
ENV_FILE=".env.test"
cat > "${ENV_FILE}" << EOF
# Test Infrastructure Configuration
# Generated by setup_test_infrastructure.sh

# Enable test infrastructure
TEST_INFRASTRUCTURE_ENABLED=true

# GCS Configuration
TEST_GCS_BUCKET=${TEST_BUCKET_NAME}
TEST_GCS_CREDENTIALS=$(pwd)/${CREDENTIALS_FILE}
GCS_PROJECT_ID=${PROJECT_ID}
GCS_REGION=${TEST_REGION}

# Supabase Configuration (update with your values)
# TEST_SUPABASE_URL=https://xxx.supabase.co
# TEST_SUPABASE_SERVICE_KEY=your_test_service_key
# Or use existing Supabase config:
# SUPABASE_URL=https://xxx.supabase.co
# SUPABASE_SERVICE_KEY=your_service_key

# Test Isolation
TEST_TENANT_ID=test_tenant
EOF

echo -e "${GREEN}✅ Configuration file created: ${ENV_FILE}${NC}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: Update ${ENV_FILE} with your Supabase credentials${NC}"

# Summary
echo ""
echo "======================================================================"
echo -e "${GREEN}✅ Test Infrastructure Setup Complete!${NC}"
echo ""
echo "Summary:"
echo "  📦 GCS Bucket: gs://${TEST_BUCKET_NAME}"
echo "  👤 Service Account: ${SERVICE_ACCOUNT_EMAIL}"
echo "  🔑 Credentials: ${CREDENTIALS_FILE}"
echo "  📝 Config: ${ENV_FILE}"
echo ""
echo "Next Steps:"
echo "  1. Update ${ENV_FILE} with Supabase credentials"
echo "  2. Add ${ENV_FILE} to .gitignore (contains credentials)"
echo "  3. Run tests: pytest tests/integration/layer_8_business_enablement/ -v"
echo ""
echo -e "${YELLOW}⚠️  Security Note: Keep ${CREDENTIALS_FILE} and ${ENV_FILE} secure!${NC}"
echo "   Add them to .gitignore to prevent committing credentials."
echo "======================================================================"

