#!/bin/bash
# Setup Test Supabase Configuration
# This script helps set up test Supabase credentials

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTS_DIR="$(dirname "$SCRIPT_DIR")"
ENV_TEST_FILE="$TESTS_DIR/.env.test"

echo "=========================================="
echo "Test Supabase Setup"
echo "=========================================="
echo ""

# Check if .env.test already exists
if [ -f "$ENV_TEST_FILE" ]; then
    echo "⚠️  .env.test already exists"
    read -p "   Overwrite? (yes/no): " overwrite
    if [ "$overwrite" != "yes" ]; then
        echo "❌ Setup cancelled"
        exit 0
    fi
fi

echo "📋 Please provide your test Supabase credentials:"
echo "   (Get these from: Supabase Dashboard → Settings → API)"
echo ""

read -p "Test Supabase URL (e.g., https://xxxxx.supabase.co): " test_url
read -p "Test Supabase Anon Key: " test_anon_key
read -p "Test Supabase Service Key: " test_service_key
read -sp "Test Database Password (optional, for migrations): " test_db_password
echo ""

read -p "Test User Email (default: test_user@symphainy.com): " test_user_email
test_user_email=${test_user_email:-test_user@symphainy.com}

read -sp "Test User Password (default: test_password_123): " test_user_password
test_user_password=${test_user_password:-test_password_123}
echo ""

read -p "Backend URL (default: http://localhost:8000): " backend_url
backend_url=${backend_url:-http://localhost:8000}

# Create .env.test file
cat > "$ENV_TEST_FILE" << EOF
# Test Environment Configuration
# Generated by setup_test_supabase.sh
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

# Test Mode Flag
TEST_MODE=true

# Test Supabase Configuration
TEST_SUPABASE_URL=$test_url
TEST_SUPABASE_ANON_KEY=$test_anon_key
TEST_SUPABASE_SERVICE_KEY=$test_service_key
TEST_SUPABASE_DB_PASSWORD=$test_db_password

# Test User Credentials
TEST_USER_EMAIL=$test_user_email
TEST_USER_PASSWORD=$test_user_password

# Backend URL
TEST_BACKEND_URL=$backend_url
EOF

echo ""
echo "✅ Test configuration saved to: $ENV_TEST_FILE"
echo ""
echo "📝 Next steps:"
echo "   1. Run migrations on test project:"
echo "      cd symphainy-platform && TEST_MODE=true python3 scripts/run_supabase_migrations.py"
echo ""
echo "   2. Start backend with test mode:"
echo "      cd symphainy-platform && TEST_MODE=true python3 main.py"
echo ""
echo "   3. Run tests:"
echo "      cd tests && TEST_MODE=true pytest e2e/production/ -v"
echo ""



